// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtNM_X7dtO06gl8emgOd6xDhYELcO5gxc',
    appId: '1:550210838458:web:9116b4c84fca5d12760783',
    messagingSenderId: '550210838458',
    projectId: 'spare-part-app-318bc',
    authDomain: 'spare-part-app-318bc.firebaseapp.com',
    databaseURL: 'https://spare-part-app-318bc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spare-part-app-318bc.firebasestorage.app',
    measurementId: 'G-775WPQ84MJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyvjNbZ7wjT-kZkvFh6SZimmPTb_4e50A',
    appId: '1:550210838458:android:349483f95ea1641b760783',
    messagingSenderId: '550210838458',
    projectId: 'spare-part-app-318bc',
    databaseURL: 'https://spare-part-app-318bc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spare-part-app-318bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8VepYliLzw_WBaKYEyWRd0JOvX_E9E3g',
    appId: '1:550210838458:ios:62fe42a811f9448d760783',
    messagingSenderId: '550210838458',
    projectId: 'spare-part-app-318bc',
    databaseURL: 'https://spare-part-app-318bc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spare-part-app-318bc.firebasestorage.app',
    iosBundleId: 'com.example.spacepart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtNM_X7dtO06gl8emgOd6xDhYELcO5gxc',
    appId: '1:550210838458:web:7ae709ab4588a365760783',
    messagingSenderId: '550210838458',
    projectId: 'spare-part-app-318bc',
    authDomain: 'spare-part-app-318bc.firebaseapp.com',
    databaseURL: 'https://spare-part-app-318bc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spare-part-app-318bc.firebasestorage.app',
    measurementId: 'G-76PRZDRDBT',
  );
}
